### ISSUE TITLE
No Function with Genesys WDE Client 8.5.127.06

### ISSUE THREAD

**Issue by trilogic-ch** [gnaudio/jabra-call-control-extension-for-genesys-workspace-desktop-edition#2]
After Updating to the latest Genesys WDE Client 8.5.127.06 the Jabra Plug-In doesn't work anymore.

Working Version: Genesys WDE Client 8.5.124.09
Non Working Version: Genesys WDE Client 8.5.127.06

Problem:
No Error Message. The Buttons of the Jabra Headset have no function anymore = Calls can't be taken or finished with the headset buttons. We have to use the mouse in WDE Client.

**Comment by frederiksen** [comment]
Possible fixed by: https://github.com/gnaudio/jabra-call-control-extension-for-genesys-workspace-desktop-edition/issues/3
