### ISSUE TITLE
Jabra Module not loading with Genesys WDE Client

### ISSUE THREAD

**Issue by asoprano** [gnaudio/jabra-call-control-extension-for-genesys-workspace-desktop-edition#3]
Hi @frederiksen ,

we tried to use the Jabra Support but we are not getting any useful response, therefore I will try it through this Issue.

We are planning to rollout the Genesys WDE (including SIP Endpoint) towards more then 400 agents. Since weeks we are having trouble with the module.

1) First of all the major problem is that the plugin seems only to work if the Genesys WDE application is installed in the default location: C:\Program Files (x86)\GCTI\Workspace Desktop Edition\
This is not the case in our setup, as we have specific requirements towards our managed application that they need to run on another location on C. 
So the first problem: Why is your Plugin only running in the default location. Even if we do not use the msi provided online but just copy the dll files into the main WDE folder it is not working. In the code we found 
<Fragment>
<Directory Id="TARGETDIR" Name="SourceDir">
<Directory Id="ProgramFilesFolder">
 <Directory Id="GCTI" Name="GCTI">
 <Directory Id="INSTALLFOLDER" Name="Workspace Desktop Edition" />
</Directory>
</Directory>
</Directory>
</Fragment>
Can you check if this is really implemented like this? Again we need to make sure that the reference is relative to the path.

2) The second problem is, even if we install the Genesys WDE application in the default location on Windows 10 C:\Program Files (x86)\GCTI\Workspace Desktop Edition\ the provided plugin with the Version: JabraCallControlExtension.dll - version 1.0.1117.0 and JabraHidTelephonyApi.dll - version 3.1.13407.0 is not working. We have Genesys WDE Application version: 8.5.129.4 and this should be supported by as mentioned on the Jabra page "8.5.x". In this case it seems that the .dll Files have some kind of dependancy that is not default on Windows 10.
Second problem: Which dependancy is required on Windows 10
We get the error message:

19-08-08 10:40:10.247 [             1] INFO  dows.LoginController - Initializing the dynamic module: JabraCallControlModule
19-08-08 10:40:10.269 [             1] ERROR dows.LoginController - An error occurs while initializing the module JabraCallControlModule. Check the <modules> and <tasks> sections in the app.exe.config file
Microsoft.Practices.Composite.Modularity.ModuleLoadException: Failed to load module JabraCallControlModule from assembly JabraCallControlExtension, Version=1.0.1117.0, Culture=neutral, PublicKeyToken=null. Error was:
Resolution of the dependency failed, type = "JabraCallControlExtension.JabraModule", name = "". Exception message is: The current build operation (build key Build Key[JabraCallControlExtension.JabraModule, null]) failed: The current build operation (build key Build Key[JabraCallControlExtension.JabraModule, null]) failed: Die Datei oder Assembly "Genesyslab.Platform.Commons, Version=9.0.0.2, Culture=neutral, PublicKeyToken=2248646200015f60" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040) (Strategy type DynamicMethodConstructorStrategy, index 0) (Strategy type BuildPlanStrategy, index 3) ---> Microsoft.Practices.Unity.ResolutionFailedException: Resolution of the dependency failed, type = "JabraCallControlExtension.JabraModule", name = "". Exception message is: The current build operation (build key Build Key[JabraCallControlExtension.JabraModule, null]) failed: The current build operation (build key Build Key[JabraCallControlExtension.JabraModule, null]) failed: Die Datei oder Assembly "Genesyslab.Platform.Commons, Version=9.0.0.2, Culture=neutral, PublicKeyToken=2248646200015f60" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040) (Strategy type DynamicMethodConstructorStrategy, index 0) (Strategy type BuildPlanStrategy, index 3) ---> Microsoft.Practices.ObjectBuilder2.BuildFailedException: The current build operation (build key Build Key[JabraCallControlExtension.JabraModule, null]) failed: The current build operation (build key Build Key[JabraCallControlExtension.JabraModule, null]) failed: Die Datei oder Assembly "Genesyslab.Platform.Commons, Version=9.0.0.2, Culture=neutral, PublicKeyToken=2248646200015f60" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040) (Strategy type DynamicMethodConstructorStrategy, index 0) (Strategy type BuildPlanStrategy, index 3) ---> Microsoft.Practices.ObjectBuilder2.BuildFailedException: The current build operation (build key Build Key[JabraCallControlExtension.JabraModule, null]) failed: Die Datei oder Assembly "Genesyslab.Platform.Commons, Version=9.0.0.2, Culture=neutral, PublicKeyToken=2248646200015f60" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040) (Strategy type DynamicMethodConstructorStrategy, index 0) ---> System.IO.FileLoadException: Die Datei oder Assembly "Genesyslab.Platform.Commons, Version=9.0.0.2, Culture=neutral, PublicKeyToken=2248646200015f60" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040) ---> System.IO.FileLoadException: Die Datei oder Assembly "Genesyslab.Platform.Commons, Version=8.5.201.6, Culture=neutral, PublicKeyToken=2248646200015f60" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
  --- Ende der internen Ausnahmestapelüberwachung ---
  bei System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
  bei System.Signature..ctor(IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
  bei System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
  bei System.Reflection.RuntimeConstructorInfo.GetParameters()
  bei Microsoft.Practices.ObjectBuilder2.ConstructorSelectorPolicyBase`1.CreateSelectedConstructor(IBuilderContext context, ConstructorInfo ctor)
  bei Microsoft.Practices.ObjectBuilder2.ConstructorSelectorPolicyBase`1.SelectConstructor(IBuilderContext context)
  bei Microsoft.Practices.ObjectBuilder2.DynamicMethodConstructorStrategy.PreBuildUp(IBuilderContext context)
  bei Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
  --- Ende der internen Ausnahmestapelüberwachung ---
  bei Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
  bei Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlanCreatorPolicy.CreatePlan(IBuilderContext context, Object buildKey)
  bei Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
  bei Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
  --- Ende der internen Ausnahmestapelüberwachung ---
  bei Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
  bei Microsoft.Practices.ObjectBuilder2.Builder.BuildUp(IReadWriteLocator locator, ILifetimeContainer lifetime, IPolicyList policies, IStrategyChain strategies, Object buildKey, Object existing)
  bei Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name)
  --- Ende der internen Ausnahmestapelüberwachung ---
  bei Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name)
  bei Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name)
  bei Microsoft.Practices.Unity.UnityContainerBase.Resolve(Type t)
  bei Microsoft.Practices.Composite.UnityExtensions.UnityContainerAdapter.Resolve(Type type)
  bei Genesyslab.Desktop.Infrastructure.ModuleLoader.CreateModule(Type type)
  bei Genesyslab.Desktop.Infrastructure.ModuleLoader.Initialize(ModuleInfo[] moduleInfos)
  --- Ende der internen Ausnahmestapelüberwachung ---
  bei Genesyslab.Desktop.Infrastructure.ModuleLoader.HandleModuleLoadError(ModuleInfo moduleInfo, String assemblyName, Exception exception)
  bei Genesyslab.Desktop.Infrastructure.ModuleLoader.Initialize(ModuleInfo[] moduleInfos)
  bei Genesyslab.Desktop.Modules.Windows.Views.Login.LoginController.LoadModules()

We are not aware of any system dependancy but maybe there is one. How would we be able to tacke this issue as it is on high priority for us.

It would be great to get some help!

Thanks a lot.

Regards
Tony Soprano

**Comment by frederiksen** [comment]
Hi @asoprano - regarding you first question. Yes you are correct about the default installation path. You have two options - either user the InstallFiles.zip and manually copy the files or I think you can overwrite the default installation folder - by adding a parameter when installing the .msi file. For your second question, do you have .NET 4 Framework installed? Or maybe there have been a braking change in the Genesys API - so a rebuild is required. It is two years since I played with this solution.

**Comment by asoprano** [comment]
Hi @frederiksen ,

thanks a lot for your quick response.
We tried to copy just the .dll files to the WDE folder, as it is usually done with all extensions implemented, but again the behavior:

1) On Windows 7: It only works correctly if placed on the default location
2) On Windows 10: It does not work at all.

On our test win10 machine we are running the following .NET Framework:
Following .Net Version is installed on this computer: .NET Framework 4.7.1 (WIN10 FallCreatorsUpdate)Release:461308
.NET Framework 4.7.1 (WIN10 FallCreatorsUpdate)Release:461308

(I used this tool - https://blog.it-koehler.com/Archive/1980)

Is there a possibility to somehow debug this stuff? We looked at the module that is references in the error message "Genesyslab.Platform.Commons, Version=9.0.0.2" and there is definitely a newer version. As you already mentioned this code is 2 years old. A further question would be if your reference is targeting the Genesyslab.Platform.Commons library in the SIP Endpoint or of the major WDE because we found two files.

Would it be possible to update some of the references and rebuild this extension? We can of course provide you with all the files you would need.

Again, thanks a lot for your response. It is much appreciated.

Regards
Tony

**Comment by frederiksen** [comment]
I think you are correct - and yes - you can debug to find the missing/or incorrect assembly. This free tool can help you: https://www.jetbrains.com/decompiler/
Try to open JabraCallControlExtension.dll with dotPeek - and find out what is wrong. And if you can share all the .dlls (via dropbox or something) - I can rebuild - and if the API has not changed - this might work.

**Comment by asoprano** [comment]
Hi @frederiksen ,

I think I identified all the referenced .dll files and uploaded them:
https://wetransfer.com/downloads/00723349b1ed9fa16e45991d2a41010320190902083322/9879c144a1c220dad19dd260df3da99b20190902083322/b56de5

Would be great to get a rebuild of the dll files. We will check if this is really the problem :-) Crossing fingers!

Regards
Tony

**Comment by frederiksen** [comment]
Thanks @asoprano - I will get back to you - I'm busy today - but expect to create a test-build in a day or two. And I'm counting on you to test - since I do not have the same setup as you.

**Comment by asoprano** [comment]
Thanks! No problem :-)

**Comment by frederiksen** [comment]
I got the time to rebuild - here's the test build: https://github.com/gnaudio/jabra-call-control-extension-for-genesys-workspace-desktop-edition/releases/tag/v1.0.5397.0

Please share the result...

**Comment by asoprano** [comment]
I have tested it successfully on Windows 10 and Win7 (default location). Let me do some final tests and I will share with you a final result.

It looks really good at the moment and I appreciate your time to update this so quickly.

**Comment by frederiksen** [comment]
Here's how to install the files to a non-default location:

`msiexec.exe /i JabraCallControlExtension.msi INSTALLFOLDER="C:\nondefaultfolder"`

The INSTALLFOLDER can also be used in i.e. System Center Configuration Manager for mass deploying.

**Comment by asoprano** [comment]
Hey!
We finally got through all setups. It is now everything working as expected.

The problem that we see: there is already newer Versions around and we tried it with a newer version and there it is already not working any more. We will need to setup a workstation where we can compile this stuff on our own otherwise we will always depend on someone (in this case you) to update the references genesys dll files.

Nevertheless it is working with our current setup. That's really great, thanks a lot for taking care and fixing this.

Regards
Tony

**Comment by frederiksen** [comment]
Thanks for the feedback. And great that we together found a solution. I will add a section in the README.md that states that the extension has dependencies to several Genesys assemblies, and these gets updated even on minor GWDE updates, so it is recommended to re-compile the extension to fit the exact GWDE version being used.
